spring:
  mail:
    host: smtp.gmail.com
    username: tranha.99884@gmail.com
    password: "bedo cevb nnkh kdpa"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true