spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: truongbb96
    password: "ewis qepe tyjd tsza"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
